Repository felixrydberg/FE21-js2-slutprojekt-hotpink, pull requests merged in 2022-03, with the labels that each got.

#1 [Add] Signin / Up html files + db connection
  src/script/modules/db.ts
  src/signin.html
  src/signup.html
Labels: new feature

#3 Sohnys branch
  src/index.html
  src/signin.html
  src/signup.html
Labels: enhancement

#4 changes
  src/index.html
  src/signin.html
  src/signup.html
Labels: enhancement

#5 Styling & profile
  src/css/profil.css
  src/css/style.css
  src/img/Gaming-setup-1024x605.webp
  src/img/bx-home.svg
  src/img/bx-search.svg
  src/img/bxs-edit-alt.svg
  src/img/bxs-log-in.svg
  src/img/bxs-log-out.svg
  src/img/homie.png
  src/img/homieass.png
  src/img/logo.svg
  src/img/profile.svg
  src/index.html
  src/profil.html
  src/signin.html
  src/signup.html
Labels: enhancement

#6 Felix dev
  src/index.html
  src/script/modules/db.ts
  src/script/modules/signfunctions.ts
  src/script/modules/user.ts
  src/script/signin.ts
  src/script/signup.ts
  src/signin.html
  src/signup.html
Labels: enhancement, new feature

#7 css
  src/css/profil.css
  src/img/bxs-edit-alt.svg
  src/signin.html
Labels: enhancement

#8 style changes
  src/css/sign.css
  src/css/style.css
  src/index.html
  src/profil.html
  src/signin.html
  src/signup.html
Labels: enhancement

#11 Sohnys branch
  src/css/style.css
  src/index.html
  src/profil.html
  src/script/main.ts
  src/script/modules/db.ts
  src/script/modules/user.ts
  src/script/profile.ts
  src/script/signin.ts
  src/script/signup.ts
  src/signin.html
  src/signup.html
Labels: enhancement

#13 Append
  src/img/signup.svg
  src/index.html
  src/profil.html
  src/script/main.ts
  src/signin.html
  src/signup.html
  tsconfig.json
Labels: enhancement

#14 Sohnys branch
  src/img/signup.svg
  src/index.html
  src/profile.html
  src/script/main.ts
  src/signin.html
  src/signup.html
Labels: enhancement

#15 Toggle/navbar
  src/css/profil.css
  src/css/sign.css
  src/css/style.css
  src/index.html
  src/profile.html
  src/script/main.ts
  src/script/modules/navtoggle.ts
  src/script/profile.ts
  src/script/signin.ts
  src/script/signup.ts
  src/signin.html
  src/signup.html
Labels: enhancement

#16 Feature - Posts
  src/css/style.css
  src/index.html
  src/profile.html
  src/script/main.ts
  src/script/modules/Post.ts
  src/script/modules/navtoggle.ts
  src/script/profile.ts
  src/script/signup.ts
  src/signin.html
  src/signup.html
  tsconfig.json
Labels: bug, enhancement, new feature

#18 Sohnys branch
  src/css/style.css
  src/profile.html
  src/script/modules/navtoggle.ts
  src/script/profile.ts
  src/script/signup.ts
  src/signin.html
  src/signup.html
Labels: enhancement

#19 Forum reworked
  src/css/style.css
  src/forum.html
  src/img/profilepic1.jpg
  src/img/profilepic2.jpg
  src/img/profilepic3.jpg
  src/index.html
  src/script/main.ts
  src/script/modules/Post.ts
  src/script/modules/forum.ts
  src/script/modules/navtoggle.ts
  src/script/profile.ts
  src/script/signup.ts
  src/signup.html
  tsconfig.json
Labels: bug

#20 [Add] Logoutbtn
  src/css/style.css
  src/forum.html
  src/index.html
  src/profile.html
  src/script/modules/navtoggle.ts
  src/script/signin.ts
  src/signin.html
  src/signup.html
Labels: enhancement, new feature

#25 Chronological order and delete account added
  src/profile.html
  src/script/modules/Post.ts
  src/script/profile.ts
  src/signup.html
Labels: bug, enhancement, new feature
