Repository felixrydberg/FE21-js2-slutprojekt-hotpink, pull requests merged in 2022-04, with the labels that each got.

#28 Felix dev
  src/css/forum.css
  src/css/sign.css
  src/css/style.css
  src/forum.html
  src/img/bx-signup.svg
  src/index.html
  src/profile.html
  src/script/modules/Post.ts
  src/script/modules/navtoggle.ts
  src/script/modules/signfunctions.ts
  src/script/modules/user.ts
  src/script/signin.ts
  src/script/signup.ts
  src/signin.html
  src/signup.html
Labels: enhancement

#29 Refactoring code and adding comments to written sections
  src/script/main.ts
  src/script/modules/Post.ts
  src/script/modules/displayBoard.ts
  src/script/modules/forum.ts
  src/script/modules/navtoggle.ts
  src/script/profile.ts
Labels: enhancement

#30 [Add] Second run of styling
  src/css/forum.css
  src/css/style.css
  src/forum.html
  src/index.html
  src/profile.html
  src/script/main.ts
  src/script/modules/displayBoard.ts
  src/signin.html
  src/signup.html
Labels: enhancement

#31 [Styling] Changed styling on message form
  src/css/forum.css
  src/css/sign.css
  src/forum.html
  src/index.html
  src/profile.html
  src/script/modules/displayBoard.ts
  src/signin.html
  src/signup.html
Labels: bug, enhancement

#33 Publication day!
  docs/bx-home.8a9c6c56.svg
  docs/bx-signup.e336e8cd.svg
  docs/bxs-log-in.e2deea63.svg
  docs/bxs-log-out.279b802c.svg
  docs/forum.47cd755e.css
  docs/forum.47cd755e.css.map
  docs/forum.c3a48231.js
  docs/forum.c3a48231.js.map
  docs/forum.html
  docs/homie.164cd7b8.png
  docs/homieass.3e86fca9.png
  docs/index.33ff48dd.css
  docs/index.33ff48dd.css.map
  docs/index.5eb5511e.js
  docs/index.5eb5511e.js.map
  docs/index.html
  docs/logo.1ef5b75c.svg
  docs/profile.15a72077.css
  docs/profile.15a72077.css.map
  docs/profile.49cfcf9f.js
  docs/profile.49cfcf9f.js.map
  docs/profile.770ff7fb.js
  docs/profile.770ff7fb.js.map
  docs/profile.7d73ebae.svg
  docs/profile.html
  docs/signin.23ddd78f.js
  docs/signin.23ddd78f.js.map
  docs/signin.55757321.js
  docs/signin.55757321.js.map
  docs/signin.9d0ec0da.css
  docs/signin.9d0ec0da.css.map
  docs/signin.html
  docs/signup.b27c6f3d.js
  docs/signup.b27c6f3d.js.map
  docs/signup.html
  package.json
  src/css/sign.css
  src/script/main.ts
  src/script/modules/displayBoard.ts
  src/script/modules/navtoggle.ts
  src/script/profile.ts
  src/script/signin.ts
  src/script/signup.ts
Labels: Publish
